language: node_js
node_js:
  - 12.11.1
services:
  - mongodb
before_script: 
  - npm install
script:  
  - npm run ci-test
after_script:
  - pkill mongod
notifications:
  slack: adaslarco:7U9BV0TVqkrvgRhMG0UAU4b3