language: node_js
node_js:
  - 12.11.1
env:
  global: 
    - JWT_SECRET=asdafsadas1234
    - MONGODB_URL=mongodb://127.0.0.1:27017/task-manager-api
services:
  - mongodb
before_script: 
  - npm install
script:
  - npm start
  - npm run ci-test